site_name: FPV Drone Build India
theme:
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    #    scheme: slate
    primary: deep purple
    accent: amber
  favicon: images/favicon.ico
  name: material
  logo: 'images/droneIcon2.png'
  features:
    - navigation.tabs
    - header.autohide
    - toc.autohide
nav:
  - Home: index.md
  - Intro:
      - Basic Drone Capabilities: 01-introduction/drone-capabilities/_index.en.md
      - Drone Regulations in India: 01-introduction/drone-regulations-ind/_index.en.md
      - Radio Communication Basics: 01-introduction/drone-rc-comms/_index.en.md
      - Basic Drone Components:
          - Component List: 01-introduction/drone-components/00-components/_index.en.md
          - Frame: 01-introduction/drone-components/01-frame/_index.en.md
          - Flight Controller: 01-introduction/drone-components/02-flight-controller/_index.en.md
          - ESC: 01-introduction/drone-components/03-esc/_index.en.md
          - Motors & Props: 01-introduction/drone-components/04-motors-props/_index.en.md
          - Batteries: 01-introduction/drone-components/05-battery/_index.en.md
          - Camera: 01-introduction/drone-components/06-camera/_index.en.md
          - Video Transmitter: 01-introduction/drone-components/07-vtx/_index.en.md
          - FPV Goggles: 01-introduction/drone-components/08-fpv-goggles/_index.en.md
          - Radio Transmitter: 01-introduction/drone-components/09-radio-tx/_index.en.md
          - Radio Receiver: 01-introduction/drone-components/10-radio-rx/_index.en.md
          - Antenna: 01-introduction/drone-components/11-antenna/_index.en.md
      - Tools Needed: 01-introduction/tools-needed/_index.en.md
  - FPV Drone Build Configs:
      - Setup 01: 02-fpv-drone-configs/build-1/_index.en.md
      - Setup 02: 02-fpv-drone-configs/build-2/_index.en.md
      - Setup 03: 02-fpv-drone-configs/build-3/_index.en.md
  - Drone Build Guide:
      - Part 01 - Getting it all together: 03-build-guide/part-1/_index.en.md
      - Part 02 - Building the frame: 03-build-guide/part-2/_index.en.md
  #     - Part 03 - The Flight Controller: 03-build-guide/part-3/_index.en.md
  #     - Part 04 - The ESC: 03-build-guide/part-4/_index.en.md
  #     - Part 05 - The Motors: 03-build-guide/part-5/_index.en.md
  #     - Part 06 - The Radio: 03-build-guide/part-6/_index.en.md
  #     - Part 07 - The Video Transmitter: 03-build-guide/part-7/_index.en.md
  #     - Part 08 - The Controller: 03-build-guide/part-8/_index.en.md
  #     - Part 09 - The Battery: 03-build-guide/part-9/_index.en.md
  #     - Part 10 - First Flight: 03-build-guide/part-10/_index.en.md
  - Indian Shopping Sites: 00-shopping-stores/_index.en.md
  - External Resources:
      - Bibliography: 04-resources/bibliography/_index.en.md
      - Resources List: 04-resources/external-list/_index.en.md
      - Drone Configuration List: 04-resources/drone-configs/_index.en.md
      - Motor Thrust Calculator: 04-resources/thrust-calc/_index.en.md
strict: true
extra:
  version: 0.5.2
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3
  - admonition
  - def_list
  - codehilite:
      linenums: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
plugins:
  - search:
      lang: en
repo_name: 'fpv-drone-build'
repo_url: 'https://github.com/sidx64/fpv-drone-build/'
edit_uri: 'tree/main/docs'
site_url: ''
